/**
 * CampusLoop University and Course Data
 * Predefined options for dropdowns and autocomplete
 */

export const CampusLoopUniversities = [
    'Harvard University',
    'Stanford University',
    'Massachusetts Institute of Technology (MIT)',
    'University of Cambridge',
    'University of Oxford',
    'University of California, Berkeley',
    'Princeton University',
    'Yale University',
    'Columbia University',
    'University of Chicago',
    'Imperial College London',
    'ETH Zurich',
    'University of Toronto',
    'National University of Singapore',
    'Tsinghua University',
    'Peking University',
    'University of Melbourne',
    'University of Sydney',
    'McGill University',
    'University of British Columbia',
    // Add more universities as needed
];

export const CampusLoopCourses = [
    'Computer Science',
    'Software Engineering',
    'Information Technology',
    'Data Science',
    'Artificial Intelligence',
    'Cybersecurity',
    'Business Administration',
    'Economics',
    'Finance',
    'Accounting',
    'Marketing',
    'Mechanical Engineering',
    'Electrical Engineering',
    'Civil Engineering',
    'Chemical Engineering',
    'Biomedical Engineering',
    'Medicine',
    'Nursing',
    'Pharmacy',
    'Psychology',
    'Sociology',
    'Political Science',
    'International Relations',
    'Law',
    'Architecture',
    'Graphic Design',
    'Fine Arts',
    'Mathematics',
    'Physics',
    'Chemistry',
    'Biology',
    'Environmental Science',
    'Education',
    'English Literature',
    'History',
    'Philosophy',
];

export const CampusLoopSemesters = [
    'Semester 1',
    'Semester 2',
    'Semester 3',
    'Semester 4',
    'Semester 5',
    'Semester 6',
    'Semester 7',
    'Semester 8',
    'Year 1',
    'Year 2',
    'Year 3',
    'Year 4',
    'Year 5',
    'Graduate Student',
    'PhD Candidate',
];

export const CampusLoopInterests = [
    'Coding',
    'Web Development',
    'Mobile Development',
    'Machine Learning',
    'Data Analysis',
    'Gaming',
    'Sports',
    'Football',
    'Basketball',
    'Tennis',
    'Swimming',
    'Gym & Fitness',
    'Music',
    'Photography',
    'Videography',
    'Reading',
    'Writing',
    'Art & Design',
    'Cooking',
    'Travel',
    'Hiking',
    'Cycling',
    'Volunteering',
    'Entrepreneurship',
    'Public Speaking',
    'Debate',
    'Theater',
    'Dance',
    'Yoga',
    'Meditation',
    'Chess',
    'Board Games',
    'Anime & Manga',
    'Movies & TV',
    'Podcasts',
];

export type CampusLoopUniversity = typeof CampusLoopUniversities[number];
export type CampusLoopCourse = typeof CampusLoopCourses[number];
export type CampusLoopSemester = typeof CampusLoopSemesters[number];
export type CampusLoopInterest = typeof CampusLoopInterests[number];
